# fly.toml app configuration file generated for server-app on 2023-09-01T18:59:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "server-app"
primary_region = "iad"
kill_timeout = "15s"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
